repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  - repo: local
    hooks:
      - id: run-tests
        name: Run tests with pytest
        entry: pytest
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-push]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--max-line-length=88"]
