name: Python Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          source venv/bin/activate
          PYTHONPATH=. pytest -m "not integration" --cov=game --cov-report=term-missing

      - name: Run Type Checking
        run: |
          source venv/bin/activate
          mypy game tests

      - name: Run Pylint
        run: |
          source venv/bin/activate
          python -m pylint game devtools map_loader.py --disable=C0114,C0116

      - name: Run Linting
        run: |
          source venv/bin/activate
          flake8 game tests

      - name: Test Asset Setup
        run: |
          source venv/bin/activate
          python scripts/setup_assets.py validate
